//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionSniper.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alerts
    {
        public System.Guid AlertID { get; set; }
        public string Description { get; set; }
        public System.DateTime TriggerTime { get; set; }
        public bool Processed { get; set; }
        public System.Guid AuctionID { get; set; }
        public bool Custom { get; set; }
        public string AlertType { get; set; }
    
        public virtual Auctions Auctions { get; set; }
    }
}
