//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionSniper.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auctions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Auctions()
        {
            this.AuctionHistory = new HashSet<AuctionHistory>();
            this.Alerts = new HashSet<Alerts>();
        }
    
        public System.Guid AuctionID { get; set; }
        public string DomainName { get; set; }
        public string AuctionRef { get; set; }
        public int BidCount { get; set; }
        public int Traffic { get; set; }
        public int Valuation { get; set; }
        public int Price { get; set; }
        public int MinBid { get; set; }
        public int MinOffer { get; set; }
        public int BuyItNow { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<System.DateTime> EstimateEndDate { get; set; }
        public System.Guid AccountID { get; set; }
        public string Status { get; set; }
        public Nullable<int> MyBid { get; set; }
        public bool Processed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuctionHistory> AuctionHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alerts> Alerts { get; set; }
    }
}
