//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionSniper.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemConfig
    {
        public string PropertyID { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }
    }
}
